### ISSUE TITLE
Error running Development build

### ISSUE THREAD

**Issue by kameshsampath** [mattmoor/mink#299]
When I try to https://github.com/mattmoor/mink/blob/master/DEVELOPMENT.md#mink-development-instructions, and to build the `mink` binary locally. I was able to build it but when running it I get the following error:

```
mink bundle --bundle=ghcr.io/kameshsampath/quarkus-mink:latest --directory=/Users/
kameshs/MyLabs/mink/quick-starts/quarkus-mink
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x23eb10f]

goroutine 1 [running]:
github.com/mattmoor/mink/pkg/kontext.Bundle(0x2aaa160, 0xc000521c20, 0x7ffeefbfef2b, 0x34, 0x0, 0x7ffeefbfeef5, 0x7, 0x7ffeefbfeefd, 0x1a, 0x7ffeefbfef18, ...)
        /Users/kameshs/git/kameshsampath/mink/pkg/kontext/bundle.go:225 +0x6f
github.com/mattmoor/mink/pkg/command.(*BundleOptions).Execute(0xc0001a36c0, 0xc00040c840, 0xc0001118e0, 0x0, 0x2, 0x0, 0x0)
        /Users/kameshs/git/kameshsampath/mink/pkg/command/bundle.go:74 +0x11a
github.com/spf13/cobra.(*Command).execute(0xc00040c840, 0xc0001118a0, 0x2, 0x2, 0xc00040c840, 0xc0001118a0)
        /Users/kameshs/git/kameshsampath/mink/vendor/github.com/spf13/cobra/command.go:834 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fd8c0, 0x1, 0x1, 0xc00040d340)
        /Users/kameshs/git/kameshsampath/mink/vendor/github.com/spf13/cobra/command.go:922 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/kameshs/git/kameshsampath/mink/vendor/github.com/spf13/cobra/command.go:872
main.main()
        /Users/kameshs/git/kameshsampath/mink/cmd/mink/main.go:164 +0x31
```

But strangely I was able to run it via  IDE :(

Any clue ??

**Comment by kameshsampath** [comment]
after setting `KO_DOCKER_REPO`, the build passed ahead but failed at 
```2020/11/30 20:24:22 failed to publish images: error building "ko://github.com/mattmoor/mink/cmd/platform-setup": error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: ``
2020/11/30 20:24:23 Using base gcr.io/distroless/static:nonroot for github.com/mattmoor/mink/cmd/extract-digest
2020/11/30 20:24:23 failed to publish images: error building "ko://github.com/mattmoor/mink/cmd/extract-digest": error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: `````

**Comment by kameshsampath** [comment]
the core issue of this failure is not 

- defining `KO_DOCKER_REPO` 
- the development machine not  having  `docker-credential-gcr` https://github.com/GoogleCloudPlatform/docker-credential-gcr

Adding them to https://github.com/mattmoor/mink/blob/master/DEVELOPMENT.md#mink-development-instructions will help.
